### ISSUE TITLE
S2 | Enhanced signup route

### ISSUE THREAD

**Issue by stephenthedev** [stephenthedev/scavenger-hunt#28]
# API Request
## Story
- As a developer
- I need an API route to Sign a user up

## Acceptance Criteria
- Route `/signup`
- Method: POST
- Request Object:

```json
{
        "email":"test@test.com",
        "password":"1234"
}
```

- Response
 
```json
{
        "id":"abcd-efgh-ijkl-mnop",
        "email":"test@test.com"
}
```

- written in a `users-api/routes/signup.js` file 
- Should validate that the mock password is at least 6 chars or more
- Should validate that the mock password includes letters and numbers (`string.match(/[a-z0-9]+/i)`)
- Should validate that the mock email includes the @ symbol and .com || .edu
- Should return a 200 if correct
- Should return a 401 with the following object if it fails any validation
```javascript
{
  "message": "Invalid Credentials"
}
```

## Approach
- Since we have no database yet, just send back example data located in this ticket.

**Comment by raghunat** [comment]
@ardagokce @shalayiding

**Comment by shalayiding** [comment]
// users-api/routes/signup.js

// Sprint 1: A mock API for signing up (#14)

//require express & create router
const express = require('express');
const router = express.Router();

// a test route
router.get('/testRoute', (req,res) => res.send('Test successful.'));

// check for content in username & password fields of body
// if data is missing, send invalid information error
// if something was entered for username and password,
// confirm the signup and display the information
router.post('/', (req, res) => {
  if(req.body.username)
  {
  if((!req.body.username) || (!req.body.password))
    {
   res.status(403).send('Invalid information.');
    }
  else
    {
   
    res.send('Account Confirmed. \n' +
    'Username: ' + req.body.username + '\n' +
    'Password: ' + req.body.password);
    }
  }
  //email 
if (req.body.email) 
  {
    var password=req.body.password;
    var Email_Check=/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
    var Email=req.body.email;
    
    if((!password)||password.length < 6||!password.match(/[a-z][0-9]+/i)||!Email_Check.test(Email))
    {
      res.status(401).send('"message": "Invalid Credentials"');
    }
    else{
      res.status(200).send(
    'id: ' + "abcd-efgh-ijkl-mnop" + '\n' +
    'email: ' + req.body.email);


    }
  } 
  else
  {
     res.status(403).send('Invalid information.');
  }
});


//export so other modules can access
module.exports = router;

**Comment by shalayiding** [comment]
i have some trouble with checking email address , if i put wwwww@gmail.ccc it still think this is valid email address.

**Comment by raghunat** [comment]
@shalayiding this has to be in proper PR format, like last sprint.

for checking emails, it doesn't have to be too strict, so I wouldn't worry about it.

**Comment by raghunat** [comment]
#39

**Comment by raghunat** [comment]
We still need this logic in the current signup route
