### ISSUE TITLE
S3 | Add a unit test for /alive in the users-api

### ISSUE THREAD

**Issue by stephenthedev** [stephenthedev/scavenger-hunt#51]
# API Request
## Story
- As a developer
- I need a bootstrapped test suite
- So that I can test my application as it changes

## Acceptance Criteria
- Mocha, should, and supertest installed in the project
- a test for GET /alive js that asserts the message given back.

- Test is written in a `users-api/test/routes/alive.js` file 
- Links for docs 
-- https://mochajs.org/
-- https://github.com/tj/should.js/
-- https://github.com/visionmedia/supertest

**Comment by raghunat** [comment]
@khan7866

**Comment by khan7866** [comment]
changes in installed dependencie
