### ISSUE TITLE
S3 | Add a unit test for the /alive route in the hunts-api

### ISSUE THREAD

**Issue by stephenthedev** [stephenthedev/scavenger-hunt#52]
# API Request
## Story
- As a developer
- I need a bootstrapped test suite
- So that I can test my application as it changes

## Acceptance Criteria
- Mocha, should, and supertest installed in the project
- a test for GET /alive js that asserts the message given back.

- Test is written in a `hunts-api/test/routes/alive.js` file 
- Links for docs 
-- https://mochajs.org/
-- https://github.com/tj/should.js/
-- https://github.com/visionmedia/supertest

**Comment by raghunat** [comment]
This is Ziwei's

**Comment by shalayiding** [comment]
//alive.js
var assert = require('assert');
const request = require('supertest');
const express = require('express');
const app = express();



app.get('/alive', function(req, res) {
  res.status(200).json({testMessage: 'This is very important Message!!!!' });
});//res status code 200 and json object testMessage


describe('GET /alive', function() {
  it('respond with json', function() {
    return request(app)
      .get('/alive')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)//make sure content type is json that we get
      .expect(200)
      .then(response =>{
        assert(response.body.testMessage);//assert testMessage
      })
  });
});

//app.listen(5000,console.log("app is on!!"));//tesing on port 5000

**Comment by shalayiding** [comment]
this is my alive.js code , i have problem with push to my own branch so post the code in here !

**Comment by raghunat** [comment]
You need to make a proper PR, otherwise code is not added correctly :-) You also need to include the new dependencies into the package.json by installing them with --save

**Comment by raghunat** [comment]
@shalayiding Still need this
