### ISSUE TITLE
S4 | Mock Recognition Client Module

### ISSUE THREAD

**Issue by stephenthedev** [stephenthedev/scavenger-hunt#71]
# Story
- As a developer,
- I want a friendly interface for processing images
- so that I can develop for it safely

# Acceptance Criteria
- A module that makes the following code work:
```js
const fs = require('fs');
const RecognitionClient = require('../service/recognition.js');

const client = new RecognitionClient();

client.analyze(fs.readFileSync('./test.png').toString('base64'))
  .then(analysis => console.log(analysis))
  .catch(e => console.error('ERROR', e));
```
- Your module should export from `image-ap/service/recognition.js`

**Comment by raghunat** [comment]
@ardagokce
